version: '3'
services:
  postgres:
    container_name: pdf_me_postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - postgres.env
    networks:
      - mainNet
    volumes:
      - dbData:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    container_name: pdf_me_pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    env_file:
      - postgres.env
    networks:
      - mainNet
    volumes:
      - pgadminData:/root/.pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pdf_me_rabbitmq
    hostname: rabbitmq
    networks:
      - mainNet
    volumes:
      - rabbitmqData:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - rabbitmq.env

  redis:
    image: "redis:alpine"
    container_name: pdf_me_redis
    networks:
      - mainNet
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pdf_me_redis-commander
    networks:
      - mainNet
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis

  cloudserver:
    container_name: pdf_me_cloudserver
    image: zenko/cloudserver
    ports:
      - '8000:8000'
    env_file:
      - cloudserver.env
    networks:
      - mainNet
    volumes:
      - cloudserverData:/usr/src/app/localData
      - cloudserverMetadata:/usr/src/app/localMetadatas

networks:
  mainNet:
    driver: bridge
volumes:
  dbData:
  rabbitmqData:
  pgadminData:
  cloudserverData:
  cloudserverMetadata:
